version: "1.0"
info:
  model: int-scaffold
packages:
- name: RAHS_GH_25thPVCycleProject
  gitServerName: RAHS_GH_IBMAccount
  gitUrl: https://github.com/rahul-singh-IBM-68
  gitUsername: rahul-singh-IBM-68
  gitBranch: main
- name: EmployeePayroll
  gitServerName: RAHS_GH_IBMAccount
  gitUrl: https://github.com/rahul-singh-IBM-68
  gitUsername: rahul-singh-IBM-68
  gitBranch: main
